Don't set BP_JVM_JLINK_ENABLED
It sometimes doesn't work for some use cases (not in this jumpstart project, but in projects that build off of it), oftentimes resulting in
errors at application startup like:
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is org.springframework.aop.framework.AopConfigException: Unable to instantiate proxy using Objenesis, and regular proxy instantiation via default constructor fails as well; nested exception is java.lang.NoSuchMethodException: [SOME CLASS].<init>()

The resulting image also cannot connect to some TLS servers.
Attempting to connect to a postgres server that offers TLS fails with:
org.postgresql.util.PSQLException: SSL error: Received fatal alert: handshake_failure

This optimization is, at least right now, not worth the effort.